/* ════════════════════════════════════════
   QUESTION BANK 
════════════════════════════════════════ */
const QB = {
  riddle: [
    {
      q: "I'm tall when young, short when old. What am I?",
      a: "candle",
      hint: "It melts over time",
      pts: 2,
    },
    {
      q: "More you take, more you leave behind. What am I?",
      a: "footsteps",
      hint: "Think about walking",
      pts: 2,
    },
    {
      q: "Has keys but can't open locks. What am I?",
      a: "piano",
      hint: "Musical instrument",
      pts: 2,
    },
    {
      q: "Has hands but can't clap. What am I?",
      a: "clock",
      hint: "Hangs on the wall",
      pts: 2,
    },
    {
      q: "I speak without a mouth and hear without ears. What am I?",
      a: "echo",
      hint: "Sound bouncing back",
      pts: 3,
    },
    {
      q: "I have cities, but no houses. I have mountains, but no trees. What am I?",
      a: "map",
      hint: "Used for navigation",
      pts: 3,
    },
    {
      q: "I am full of holes but can still hold water. What am I?",
      a: "sponge",
      hint: "Used for cleaning",
      pts: 2,
    },
    {
      q: "Forward I am heavy, but backward I am not. What am I?",
      a: "ton",
      hint: "Think about the spelling",
      pts: 4,
    },
    {
      q: "What has to be broken before you can use it?",
      a: "egg",
      hint: "A common breakfast food",
      pts: 2,
    },
    {
      q: "Drop me from the tallest building and I'll survive, drop me in water and I die. What am I?",
      a: "paper",
      hint: "You write on it",
      pts: 4,
    },
    {
      q: "I have teeth but cannot bite. What am I?",
      a: "comb",
      hint: "Used for your hair",
      pts: 2,
    },
    {
      q: "What goes up but never comes down?",
      a: "age",
      hint: "It happens every birthday",
      pts: 2,
    },
    {
      q: "I can be cracked, made, told, and played. What am I?",
      a: "joke",
      hint: "Makes you laugh",
      pts: 3,
    },
    {
      q: "What gets wetter the more it dries?",
      a: "towel",
      hint: "Used after a shower",
      pts: 2,
    },
    {
      q: "What has words, but never speaks?",
      a: "book",
      hint: "You read it",
      pts: 2,
    },
    {
      q: "I have a tail and a head, but no body. What am I?",
      a: "coin",
      hint: "Used to buy things",
      pts: 2,
    },
    {
      q: "What has a neck but no head?",
      a: "bottle",
      hint: "Holds liquids",
      pts: 2,
    },
    {
      q: "What begins with T, ends with T, and has T in it?",
      a: "teapot",
      hint: "Used to serve a hot drink",
      pts: 3,
    },
    {
      q: "You see me once in June, twice in November, but not at all in May. What am I?",
      a: "e",
      hint: "Think about the spelling of the months",
      pts: 4,
    },
    {
      q: "What has a thumb and four fingers, but is not alive?",
      a: "glove",
      hint: "Keeps your hands warm",
      pts: 2,
    },
  ],

  emoji: [
    {
      imgs: ["flame", "brick-wall"],
      a: "firewall",
      hint: "Protects computers",
      pts: 2,
    },
    { imgs: ["key", "keyboard"], a: "keyboard", hint: "For typing", pts: 2 },
    {
      imgs: ["sun", "flower"],
      a: "sunflower",
      hint: "Follows the sun",
      pts: 2,
    },
    {
      imgs: ["footprints", "circle-dot"],
      a: "football",
      hint: "Popular sport",
      pts: 2,
    },
    { imgs: ["book", "bug"], a: "bookworm", hint: "Loves reading", pts: 3 },
    {
      imgs: ["moon", "lightbulb"],
      a: "moonlight",
      hint: "Nighttime glow",
      pts: 3,
    },
    { imgs: ["star", "🐠"], a: "starfish", hint: "Ocean creature", pts: 2 },
    {
      imgs: ["eye", "droplet"],
      a: "teardrop",
      hint: "Comes from crying",
      pts: 3,
    },
    { imgs: ["🌲", "🍎"], a: "pineapple", hint: "Tropical fruit", pts: 3 },
    {
      imgs: ["🚗", "🐶"],
      a: "carpet",
      hint: "Found on floors (Car + Pet)",
      pts: 4,
    },
    { imgs: ["mail", "box"], a: "mailbox", hint: "Receives letters", pts: 2 },
    { imgs: ["cloud", "zap"], a: "thunderstorm", hint: "Bad weather", pts: 2 },
    { imgs: ["bell", "👦"], a: "bellboy", hint: "Works at a hotel", pts: 4 },
    // --- New Icon Matches ---
    {
      imgs: ["sun", "glasses"],
      a: "sunglasses",
      hint: "Worn on bright days",
      pts: 2,
    },
    {
      imgs: ["❄️", "⚽"],
      a: "snowball",
      hint: "Used in winter fights",
      pts: 2,
    },
    {
      imgs: ["coffee", "🍰"],
      a: "coffeecake",
      hint: "A sweet morning treat",
      pts: 3,
    },
    {
      imgs: ["🚗", "💦"],
      a: "carwash",
      hint: "Keeps your vehicle clean",
      pts: 2,
    },
    {
      imgs: ["🌧️", "🎀"],
      a: "rainbow",
      hint: "Colorful sky arch (Rain + Bow)",
      pts: 3,
    },
    { imgs: ["🔥", "🪰"], a: "firefly", hint: "A glowing insect", pts: 3 },
    {
      imgs: ["🍳", "🍰"],
      a: "pancake",
      hint: "Breakfast food with syrup",
      pts: 3,
    },
    { imgs: ["🔥", "🐶"], a: "hotdog", hint: "Stadium snack", pts: 2 },
    { imgs: ["🧺", "⚽"], a: "basketball", hint: "Shoot hoops", pts: 2 },
    {
      imgs: ["💦", "🍈"],
      a: "watermelon",
      hint: "Green outside, red inside fruit",
      pts: 2,
    },
    {
      imgs: ["🧠", "📱"],
      a: "smartphone",
      hint: "The device in your pocket",
      pts: 3,
    },
    {
      imgs: ["star", "🚢"],
      a: "starship",
      hint: "Travels through space",
      pts: 3,
    },
  ],

  trivia: [
    {
      q: "Capital of Australia?",
      opts: ["Sydney", "Melbourne", "Canberra", "Brisbane"],
      a: 2,
      cat: "Geography",
      pts: 2,
    },
    {
      q: "Which planet is closest to the Sun?",
      opts: ["Venus", "Earth", "Mercury", "Mars"],
      a: 2,
      cat: "Space",
      pts: 2,
    },
    {
      q: "Chemical symbol for gold?",
      opts: ["Gd", "Go", "Au", "Ag"],
      a: 2,
      cat: "Chemistry",
      pts: 3,
    },
    {
      q: "Longest river in the world?",
      opts: ["Amazon", "Congo", "Nile", "Yangtze"],
      a: 2,
      cat: "Geography",
      pts: 2,
    },
    {
      q: "Smallest country in the world?",
      opts: ["Monaco", "Vatican City", "San Marino", "Liechtenstein"],
      a: 1,
      cat: "Geography",
      pts: 3,
    },
    {
      q: "Who painted the Mona Lisa?",
      opts: [
        "Vincent van Gogh",
        "Pablo Picasso",
        "Leonardo da Vinci",
        "Claude Monet",
      ],
      a: 2,
      cat: "Art",
      pts: 2,
    },
    {
      q: "How many bones are in the adult human body?",
      opts: ["196", "206", "216", "226"],
      a: 1,
      cat: "Biology",
      pts: 3,
    },
    {
      q: "In what year did the Titanic sink?",
      opts: ["1905", "1912", "1920", "1931"],
      a: 1,
      cat: "History",
      pts: 3,
    },
    // --- New Trivia ---
    {
      q: "Which ocean is the largest on Earth?",
      opts: ["Atlantic", "Indian", "Arctic", "Pacific"],
      a: 3,
      cat: "Geography",
      pts: 2,
    },
    {
      q: "What is the capital city of Japan?",
      opts: ["Seoul", "Beijing", "Tokyo", "Bangkok"],
      a: 2,
      cat: "Geography",
      pts: 2,
    },
    {
      q: "Who wrote the play 'Romeo and Juliet'?",
      opts: [
        "Charles Dickens",
        "William Shakespeare",
        "Jane Austen",
        "Mark Twain",
      ],
      a: 1,
      cat: "Literature",
      pts: 2,
    },
    {
      q: "What is the largest mammal on Earth?",
      opts: ["Elephant", "Giraffe", "Blue Whale", "Great White Shark"],
      a: 2,
      cat: "Biology",
      pts: 2,
    },
    {
      q: "How many continents are there on Earth?",
      opts: ["5", "6", "7", "8"],
      a: 2,
      cat: "Geography",
      pts: 2,
    },
    {
      q: "Which country is known as the Land of the Rising Sun?",
      opts: ["China", "South Korea", "Japan", "Vietnam"],
      a: 2,
      cat: "Geography",
      pts: 2,
    },
    {
      q: "What is the national animal of India?",
      opts: ["Lion", "Tiger", "Elephant", "Peacock"],
      a: 1,
      cat: "Nature",
      pts: 2,
    },
    {
      q: "In what sport do you hit a shuttlecock?",
      opts: ["Tennis", "Table Tennis", "Squash", "Badminton"],
      a: 3,
      cat: "Sports",
      pts: 2,
    },
    {
      q: "How many colors are in a standard rainbow?",
      opts: ["5", "6", "7", "8"],
      a: 2,
      cat: "Nature",
      pts: 2,
    },
    {
      q: "Which fictional city is the home of Batman?",
      opts: ["Metropolis", "Gotham", "Star City", "Central City"],
      a: 1,
      cat: "Pop Culture",
      pts: 2,
    },
  ],

  math: [
    { q: "17 × 8 = ?", a: "136", hint: "Try 17×8 = 17×4×2", pts: 2 },
    { q: "Square root of 169?", a: "13", hint: "13 × 13 = 169", pts: 3 },
    { q: "25% of 200?", a: "50", hint: "Divide by 4", pts: 2 },
    { q: "2⁸ = ?", a: "256", hint: "Double 128", pts: 3 },
    { q: "144 ÷ 12 = ?", a: "12", hint: "It's a dozen dozens", pts: 2 },
    {
      q: "If x + 7 = 15, what is x?",
      a: "8",
      hint: "Subtract 7 from both sides",
      pts: 2,
    },
    {
      q: "What is the next prime number after 23?",
      a: "29",
      hint: "It only has two factors",
      pts: 4,
    },
    {
      q: "What is 7 factorial (7!)?",
      a: "5040",
      hint: "7 × 6 × 5 × 4 × 3 × 2 × 1",
      pts: 4,
    },
    // --- New Math ---
    { q: "50 + 75 = ?", a: "125", hint: "Add 50 to 70, then add 5", pts: 2 },
    { q: "100 - 33 = ?", a: "67", hint: "Subtract 30, then 3", pts: 2 },
    { q: "12 × 12 = ?", a: "144", hint: "A gross amount", pts: 2 },
    { q: "64 ÷ 8 = ?", a: "8", hint: "8 times what is 64?", pts: 2 },
    { q: "What is 10% of 500?", a: "50", hint: "Drop one zero", pts: 2 },
    {
      q: "Next number in the sequence: 2, 4, 8, 16, ...?",
      a: "32",
      hint: "Multiply by 2",
      pts: 3,
    },
    {
      q: "How many degrees are in a right angle?",
      a: "90",
      hint: "A perfect corner",
      pts: 2,
    },
    { q: "5³ (5 cubed) = ?", a: "125", hint: "5 × 5 × 5", pts: 3 },
    { q: "What is half of 250?", a: "125", hint: "Divide by 2", pts: 2 },
    { q: "Solve for x: 2x = 18", a: "9", hint: "Divide 18 by 2", pts: 2 },
  ],

  science: [
    {
      q: "Powerhouse of the cell?",
      opts: ["Nucleus", "Ribosome", "Mitochondria", "Chloroplast"],
      a: 2,
      cat: "Biology",
      pts: 2,
    },
    {
      q: "Chemical formula for water?",
      opts: ["HO", "H₂O", "H₃O", "OH₂"],
      a: 1,
      cat: "Chemistry",
      pts: 2,
    },
    {
      q: "Most abundant element in the universe?",
      opts: ["Oxygen", "Carbon", "Helium", "Hydrogen"],
      a: 3,
      cat: "Astronomy",
      pts: 2,
    },
    {
      q: "What is the hardest natural substance on Earth?",
      opts: ["Gold", "Iron", "Diamond", "Platinum"],
      a: 2,
      cat: "Geology",
      pts: 2,
    },
    {
      q: "What gas do plants primarily absorb from the atmosphere?",
      opts: ["Oxygen", "Nitrogen", "Carbon Dioxide", "Hydrogen"],
      a: 2,
      cat: "Biology",
      pts: 2,
    },
    {
      q: "What force keeps the planets in orbit around the Sun?",
      opts: ["Magnetism", "Friction", "Gravity", "Tension"],
      a: 2,
      cat: "Physics",
      pts: 2,
    },
    {
      q: "What is the study of weather called?",
      opts: ["Geology", "Meteorology", "Ecology", "Astronomy"],
      a: 1,
      cat: "Earth Science",
      pts: 3,
    },
    {
      q: "Which planet is known as the Red Planet?",
      opts: ["Venus", "Jupiter", "Mars", "Saturn"],
      a: 2,
      cat: "Astronomy",
      pts: 2,
    },
    {
      q: "What is the chemical symbol for Oxygen?",
      opts: ["Ox", "O", "Oxg", "O2"],
      a: 1,
      cat: "Chemistry",
      pts: 2,
    },
    {
      q: "At what temperature does water freeze (in Celsius)?",
      opts: ["0", "32", "100", "-10"],
      a: 0,
      cat: "Physics",
      pts: 2,
    },
    {
      q: "What part of the plant conducts photosynthesis?",
      opts: ["Root", "Stem", "Leaf", "Flower"],
      a: 2,
      cat: "Biology",
      pts: 2,
    },
    {
      q: "What is the center of an atom called?",
      opts: ["Proton", "Electron", "Nucleus", "Molecule"],
      a: 2,
      cat: "Chemistry",
      pts: 2,
    },
    {
      q: "How many planets are currently recognized in our solar system?",
      opts: ["7", "8", "9", "10"],
      a: 1,
      cat: "Astronomy",
      pts: 2,
    },
    {
      q: "What gas do humans primarily breathe out?",
      opts: ["Oxygen", "Carbon Monoxide", "Carbon Dioxide", "Nitrogen"],
      a: 2,
      cat: "Biology",
      pts: 2,
    },
    {
      q: "Through which medium does sound travel the fastest?",
      opts: ["Air", "Water", "Solid Space", "Vacuum"],
      a: 2,
      cat: "Physics",
      pts: 3,
    },
    {
      q: "What is the closest star to Earth?",
      opts: ["Sirius", "Alpha Centauri", "The Sun", "Proxima Centauri"],
      a: 2,
      cat: "Astronomy",
      pts: 2,
    },
    {
      q: "What pigment gives plants their green color?",
      opts: ["Melanin", "Chlorophyll", "Carotene", "Anthocyanin"],
      a: 1,
      cat: "Biology",
      pts: 2,
    },
  ],
};
